### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mysticw**
The line add-apt-repository -y ppa:rquillo/ansible/ubuntu returns 'Please check that the PPA name or format is correct.' removing the /ubuntu allows the install to continue.

### CODE REVIEW

**Comment by eosrei** [comment]
Thanks @mysticw ! The `install.sh` is correct, but the readme isn't. Haha! Could you rebase the commit message to be more descriptive?

If you haven't rebased before:

1. `git rebase -i 7fe410a6` ID of commit to start interactive rebase from, last commit on master in this case.
2. It starts your default text editor. Type "edit" in front of your commit.
3. Save and exit your editor (nano, vim, etc)
4. `git commit --amend` Recommits the commit and brings up your editor with the original commit message.
5. Edit the message and save.
6. `git rebase --continue` To finish the rebase
7. `git push -f` Force update your branch so I can merge it.

**Comment by mysticw** [comment]
@eosrei , Everything went okay until I tried 'git push -f' now I have a host of errors and it says there is nothing to commit.

What do you see (yes, I have never done this before)

**Comment by eosrei** [comment]
@mysticw Haha no problem you've got to learn it some time. It's really useful. What errors? It's git so everything is revertable.

**Comment by mysticw** [comment]
@eosrei , Thanks Brad. We met at BADcamp, I'm a friend of Eric Casequin and David Needham.

Sorry for the big post, but here is what is happening:

john@MWd-Studios-MBP ~/git-dev-workflow $ git rebase -i 7fe410a6

It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr "/Users/john/git-dev-workflow/.git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.
john@MWd-Studios-MBP ~/git-dev-workflow $ rm -fr "/Users/john/git-dev-workflow/.git/rebase-merge"
john@MWd-Studios-MBP ~/git-dev-workflow $ git rebase -i 7fe410a6
Unknown command: enoop  
Please fix this using 'git rebase --edit-todo'.
john@MWd-Studios-MBP ~/git-dev-workflow $ git rebase --edit-todo
john@MWd-Studios-MBP ~/git-dev-workflow $ git commit --amend
[detached HEAD 48d5807] Update README.md
 Author: Brad Erickson <eosrei@gmail.com>
 Date: Thu May 21 11:13:21 2015 -0700
 1 file changed, 1 insertion(+), 2 deletions(-)
john@MWd-Studios-MBP ~/git-dev-workflow $ git rebase --continue
cat: /Users/john/git-dev-workflow/.git/rebase-merge/stopped-sha: No such file or directory
fatal: Needed a single revision
Invalid commit name: 
john@MWd-Studios-MBP ~/git-dev-workflow $ git push -f
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

john@MWd-Studios-MBP ~/git-dev-workflow $ git status
rebase in progress; onto 7fe410a
You are currently editing a commit during a rebase.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working directory clean
john@MWd-Studios-MBP ~/git-dev-workflow $ git rebase --continue
cat: /Users/john/git-dev-workflow/.git/rebase-merge/stopped-sha: No such file or directory
Successfully rebased and updated detached HEAD.
john@MWd-Studios-MBP ~/git-dev-workflow $ git push -f
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

john@MWd-Studios-MBP ~/git-dev-workflow $ git status
Not currently on any branch.
nothing to commit, working directory clean
john@MWd-Studios-MBP ~/git-dev-workflow $ git push -f
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

john@MWd-Studios-MBP ~/git-dev-workflow $ git push origin Head:mysticw/git-dev-workflow
error: unable to push to unqualified destination: mysticw/git-dev-workflow
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'git@github.com:mysticw/git-dev-workflow.git'
john@MWd-Studios-MBP ~/git-dev-workflow $ git status
Not currently on any branch.
nothing to commit, working directory clean
john@MWd-Studios-MBP ~/git-dev-workflow $ git push origin HEAD:git-dev-workflow
error: unable to push to unqualified destination: git-dev-workflow
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'git@github.com:mysticw/git-dev-workflow.git'
john@MWd-Studios-MBP ~/git-dev-workflow $ git push origin HEAD:git-dev-workflow.git
error: unable to push to unqualified destination: git-dev-workflow.git
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'git@github.com:mysticw/git-dev-workflow.git'
john@MWd-Studios-MBP ~/git-dev-workflow $ git push origin HEAD:eosrei/git-dev-workflow.git
error: unable to push to unqualified destination: eosrei/git-dev-workflow.git
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'git@github.com:mysticw/git-dev-workflow.git'

**Comment by eosrei** [comment]
Yep, I remember you!
```
I wonder if you are in the middle of another rebase.  If that is the
case, please try
    git rebase (--continue | --abort | --skip)
```
I'd start with it's first suggestion rather than deleting stuff. Plus, this only happens if you've started a rebase already.
```
john@MWd-Studios-MBP ~/git-dev-workflow $ git status
Not currently on any branch.
```
You need to get on a branch.
```bash
$ git checkout patch-1 # Name this better for your own sanity in the future ;)
```
then check the git status. Need to be clean on your branch. Then do the above again.

**Comment by mysticw** [comment]
Ok,

john@MWd-Studios-MBP ~/git-dev-workflow $ git status
On branch patch-1
Your branch is up-to-date with 'origin/patch-1'.
nothing to commit, working directory clean

Do I now need to start at the top of the instructions to proceed?

**Comment by eosrei** [comment]
Yes.

**Comment by mysticw** [comment]
YES! That worked, Thanks @eosrei !

**Comment by eosrei** [comment]
But your commit message still doesn't give details. I (as a developer, not just me) should never have to look at a commit to understand why it exists.

"Correct PPA path for Ansible in README.md"
"Update README.md with working Ansible PPA"

Like that. :)

**Comment by mysticw** [comment]
so now i edit my /private/etc/hosts file to add the ip address of the site?



Thanks,

John Mcmillian

**Comment by eosrei** [comment]
Email me, open another issue, or contact me on IRC/gchat for a different subject. Let's not clutter this issue.

**Comment by mysticw** [comment]
Oh, will correct that. Thanks

Thanks,

John Mcmillian

**Comment by mysticw** [comment]
Ok, this looks as if it has worked, whew. I'll get the hang of it.

**Comment by eosrei** [comment]
Great! Thanks!

**Pull request merged**
